// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD634HIiXbUkwuAaZHXBPjO-LkxbfReCAw',
    appId: '1:84349545253:web:35f091c1b1676baeb248cc',
    messagingSenderId: '84349545253',
    projectId: 'expense--tracker-6c105',
    authDomain: 'expense--tracker-6c105.firebaseapp.com',
    storageBucket: 'expense--tracker-6c105.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-QB8k7BNHFhtH-dDUXDRYEOfKprWjK0s',
    appId: '1:84349545253:android:ad36873b320d578fb248cc',
    messagingSenderId: '84349545253',
    projectId: 'expense--tracker-6c105',
    storageBucket: 'expense--tracker-6c105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFEW69j4OsYSFrvd7LmskORobEZVVURg',
    appId: '1:84349545253:ios:36bb07fc2d3e6894b248cc',
    messagingSenderId: '84349545253',
    projectId: 'expense--tracker-6c105',
    storageBucket: 'expense--tracker-6c105.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDFEW69j4OsYSFrvd7LmskORobEZVVURg',
    appId: '1:84349545253:ios:36bb07fc2d3e6894b248cc',
    messagingSenderId: '84349545253',
    projectId: 'expense--tracker-6c105',
    storageBucket: 'expense--tracker-6c105.firebasestorage.app',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD634HIiXbUkwuAaZHXBPjO-LkxbfReCAw',
    appId: '1:84349545253:web:d6808762649b598eb248cc',
    messagingSenderId: '84349545253',
    projectId: 'expense--tracker-6c105',
    authDomain: 'expense--tracker-6c105.firebaseapp.com',
    storageBucket: 'expense--tracker-6c105.firebasestorage.app',
  );
}
